version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-pkg-cache
      - run: ls -alh 
      - run: pwd
      - run: ci/test.sh $(go list ./... | grep -v vendor)
      - save_cache:
          key: v1-pkg-cache
          paths:
          - ~/.cache/go-build

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build
